apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlc-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dlc-tf-tensorflow
spec:
  containers:
  - name: dlc-tf-tensorflow
    image: gcr.io/deeplearning-platform-release/tf2-cpu.2-0 
    volumeMounts:
      - name: dlc-tensorflow-volume
        mountPath: /home
  volumes:
  - name: dlc-tensorflow-volume
    persistentVolumeClaim:
      claimName: dlc-persistent-tensorflow-volume-claim